# -*- coding: utf-8 -*-
"""radar_snapshot_gen.py -- AIHOT /api/v1/dailies/latest -> window.RADAR_DAILY JS snapshot.

Metaverse embed data generator (R-20261010-bigstream-04 appendix A production
version, unlocked by group decision D-20261010-09: BigStream delivers the
generator + first snapshot, MiniGame integrates the consuming module).

Red lines enforced in code:
- Internal-anchor scrub: report-level links.aihot and attribution.url
  (127.0.0.1 endpoints) never reach the JS file; story cards keep only
  links.original + source.name (the "no source, no publish" consumption slot).
- Hard gate: if any internal anchor survives into the rendered payload the
  run fails (rc 4) and no file is written -- belt-and-braces after the scrub.
- Honest empty state: an empty day (sections=[] flashes=[]) or a missing
  report renders as-is with available=false / empty arrays; no fabricated
  data ever (spec section 4, "jin jia data" prohibition).
- AIGC marker: the file header declares itself AI-generated content.

Exit codes: 0 ok / 2 fetch-parse or usage error / 4 internal-anchor gate.
"""
import argparse
import io
import json
import os
import socket
import sys
import urllib.error
import urllib.request

DEFAULT_API = "http://127.0.0.1:3101"
LATEST_PATH = "/api/v1/dailies/latest"
DEFAULT_TIMEOUT = 10.0
# Internal host markers that must never appear in the outward-visible file.
INTERNAL_MARKERS = ("127.0.0.1", "localhost:3")
HEADER_LINES = (
    "// radar-daily-data.js -- generated by tools/radar_snapshot_gen.py"
    " (BigStream, R-20261010-04 appendix A / D-20261010-09)\n"
    "// AI-generated content (AIGC), based on public hot lists;"
    " attribution name carried in payload.attributionName.\n"
)


class RadarSnapshotError(Exception):
    """Base error for the snapshot generator."""


class RadarFetchError(RadarSnapshotError):
    """API unreachable / bad payload (HTTP, timeout, non-JSON)."""


class InternalAnchorError(RadarSnapshotError):
    """An internal-only anchor survived the scrub into the payload."""


def fetch_latest(api_base, timeout):
    """GET <api_base>/api/v1/dailies/latest -> parsed JSON object."""
    url = api_base.rstrip("/") + LATEST_PATH
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            raw = resp.read()
    except (urllib.error.URLError, socket.timeout, OSError) as exc:
        raise RadarFetchError("%s: %s" % (url, exc))
    try:
        data = json.loads(raw.decode("utf-8"))
    except (ValueError, UnicodeDecodeError) as exc:
        raise RadarFetchError("%s: bad JSON: %s" % (url, exc))
    if not isinstance(data, dict):
        raise RadarFetchError("%s: expected a JSON object" % url)
    return data


def _scrub_internal_anchors(obj):
    """Recursively strip internal-only anchors.

    - any dict key "links" keeps only "original" (dropped entirely when the
      original link is absent);
    - any dict key "attribution" keeps only "name";
    everything else recurses untouched.
    """
    if isinstance(obj, dict):
        out = {}
        links = obj.get("links")
        if isinstance(links, dict) and "original" in links:
            out["links"] = {"original": links.get("original")}
        attribution = obj.get("attribution")
        if isinstance(attribution, dict):
            out["attribution"] = {"name": attribution.get("name")}
        for key, value in obj.items():
            if key in ("links", "attribution"):
                continue
            out[key] = _scrub_internal_anchors(value)
        return out
    if isinstance(obj, list):
        return [_scrub_internal_anchors(item) for item in obj]
    return obj


def build_payload(data):
    """Project the API payload into the embed schema (spec section 4 mapping)."""
    rep = data.get("report") or {}
    if not isinstance(rep, dict):
        rep = {}
    date = rep.get("date")
    available = bool(date)
    lead = None
    raw_lead = rep.get("lead")
    if available and isinstance(raw_lead, dict):
        lead = {
            "title": raw_lead.get("title"),
            "leadParagraph": raw_lead.get("leadParagraph"),
        }
    sections = []
    raw_sections = rep.get("sections") or []
    if isinstance(raw_sections, list):
        for sec in raw_sections:
            if not isinstance(sec, dict):
                continue
            items = []
            for it in (sec.get("items") or []):
                if not isinstance(it, dict):
                    continue
                links = it.get("links") or {}
                items.append({
                    "title": it.get("title"),
                    "summary": it.get("summary"),
                    "source": (it.get("source") or {}).get("name"),
                    "original": links.get("original") if isinstance(links, dict) else None,
                })
            sections.append({"label": sec.get("label"), "items": items})
    raw_flashes = rep.get("flashes") or []
    flashes = _scrub_internal_anchors(raw_flashes) if isinstance(raw_flashes, list) else []
    attribution = rep.get("attribution") or {}
    return {
        "schemaVersion": data.get("schemaVersion"),
        "available": available,
        "date": date,
        "generatedAt": rep.get("generatedAt"),
        "attributionName": attribution.get("name") if isinstance(attribution, dict) else None,
        "lead": lead,
        "sections": sections,
        "flashes": flashes,
    }


def assert_no_internal_anchors(payload):
    """Hard gate: no internal host marker anywhere in the rendered payload."""
    blob = json.dumps(payload, ensure_ascii=False)
    for marker in INTERNAL_MARKERS:
        if marker in blob:
            raise InternalAnchorError("marker %r found in payload" % marker)


def render_js(payload):
    """Render the window.RADAR_DAILY assignment (UTF-8, LF, JSON body)."""
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    # U+2028/U+2029 are valid JSON but break JS string literals.
    body = body.replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    return HEADER_LINES + "window.RADAR_DAILY = " + body + ";\n"


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    ap = argparse.ArgumentParser(
        description="AIHOT dailies/latest -> window.RADAR_DAILY JS snapshot")
    ap.add_argument("--api", default=DEFAULT_API,
                    help="AIHOT api base url (default %(default)s)")
    ap.add_argument("--out", required=True,
                    help="output JS data file path (e.g. radar-daily-data.js)")
    ap.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT,
                    help="fetch timeout seconds (default %(default)s)")
    args = ap.parse_args(argv)
    if args.timeout <= 0:
        print("ERROR: --timeout must be positive", file=sys.stderr)
        return 2
    try:
        data = fetch_latest(args.api, args.timeout)
    except RadarFetchError as exc:
        print("ERROR: fetch failed: %s" % exc, file=sys.stderr)
        return 2
    payload = build_payload(data)
    try:
        assert_no_internal_anchors(payload)
    except InternalAnchorError as exc:
        print("ERROR: internal-anchor gate: %s" % exc, file=sys.stderr)
        return 4
    out_dir = os.path.dirname(os.path.abspath(args.out))
    if out_dir:
        try:
            os.makedirs(out_dir, exist_ok=True)
        except OSError as exc:
            print("ERROR: cannot create output dir: %s" % exc, file=sys.stderr)
            return 2
    try:
        with io.open(args.out, "w", encoding="utf-8", newline="\n") as f:
            f.write(render_js(payload))
    except OSError as exc:
        print("ERROR: cannot write %s: %s" % (args.out, exc), file=sys.stderr)
        return 2
    print("WROTE %s date=%s available=%s sections=%d flashes=%d" % (
        args.out, payload["date"], payload["available"],
        len(payload["sections"]), len(payload["flashes"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
